# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models, layers, utils
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [2]:
#Loading Data
df = pd.read_csv('data/iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
#Shuffling Data
df = shuffle(df)
df.head()

sepal.length  sepal.width  petal.length  petal.width    variety
118           7.7          2.6           6.9          2.3  Virginica
13            4.3          3.0           1.1          0.1     Setosa
134           6.1          2.6           5.6          1.4  Virginica
42            4.4          3.2           1.3          0.2     Setosa
128           6.4          2.8           5.6          2.1  Virginica

In [4]:
#Converting data into numpy array
data = df.values
print(data.dtype)
print(data)

object
[[7.7 2.6 6.9 2.3 'Virginica']
 [4.3 3.0 1.1 0.1 'Setosa']
 [6.1 2.6 5.6 1.4 'Virginica']
 [4.4 3.2 1.3 0.2 'Setosa']
 [6.4 2.8 5.6 2.1 'Virginica']
 [5.0 3.2 1.2 0.2 'Setosa']
 [5.5 2.5 4.0 1.3 'Versicolor']
 [6.3 3.4 5.6 2.4 'Virginica']
 [5.4 3.4 1.5 0.4 'Setosa']
 [6.3 2.3 4.4 1.3 'Versicolor']
 [6.6 3.0 4.4 1.4 'Versicolor']
 [6.3 2.8 5.1 1.5 'Virginica']
 [5.7 4.4 1.5 0.4 'Setosa']
 [5.0 2.0 3.5 1.0 'Versicolor']
 [5.7 2.8 4.1 1.3 'Versicolor']
 [5.9 3.0 5.1 1.8 'Virginica']
 [6.3 2.5 4.9 1.5 'Versicolor']
 [5.7 2.9 4.2 1.3 'Versicolor']
 [6.4 3.2 5.3 2.3 'Virginica']
 [5.4 3.4 1.7 0.2 'Setosa']
 [5.1 3.3 1.7 0.5 'Setosa']
 [4.6 3.2 1.4 0.2 'Setosa']
 [5.4 3.9 1.3 0.4 'Setosa']
 [7.9 3.8 6.4 2.0 'Virginica']
 [5.2 2.7 3.9 1.4 'Versicolor']
 [6.1 2.8 4.7 1.2 'Versicolor']
 [6.4 2.9 4.3 1.3 'Versicolor']
 [5.5 2.3 4.0 1.3 'Versicolor']
 [7.7 3.0 6.1 2.3 'Virginica']
 [5.2 3.4 1.4 0.2 'Setosa']
 [6.4 3.1 5.5 1.8 'Virginica']
 [5.1 3.7 1.5 0.4 'Setosa']
 [6.5 3.0 5.2 2.0 'Virg

In [5]:
data.shape

(150, 5)

In [6]:
#Splitting labels from data
x = data[:,:4].astype('float32')
y = data[:,4]
print(x[0])
print(y[0])

[7.7 2.6 6.9 2.3]
Virginica


In [7]:
#splitting data & labels into training and testing datasets
train_data = x[:105,:] #70% training
train_labels = y[:105]
test_data = x[105:,:] #30% testing
test_labels = y[105:]
print('Train Data: ',train_data.shape)
print('Test Data: ',test_data.shape)

Train Data:  (105, 4)
Test Data:  (45, 4)


In [8]:
#encoding string labels into integers
le = LabelEncoder()
le.fit(train_labels)
class_train_labels = le.transform(train_labels)
print(class_train_labels)

[2 0 2 0 2 0 1 2 0 1 1 2 0 1 1 2 1 1 2 0 0 0 0 2 1 1 1 1 2 0 2 0 2 1 0 0 2
 0 0 1 2 1 2 1 0 2 1 1 2 0 2 1 2 0 2 2 2 0 1 0 1 1 2 2 2 0 1 0 1 0 0 1 2 1
 1 2 1 1 2 2 2 0 2 2 0 0 2 1 2 1 2 1 0 1 2 0 0 0 1 2 0 1 1 0 2]


In [9]:
print(le.classes_)

['Setosa' 'Versicolor' 'Virginica']


In [10]:
le.fit(test_labels)
le.fit(test_labels)
class_test_labels = le.transform(test_labels)
print(class_test_labels)

[1 0 0 2 2 0 1 2 1 1 2 1 0 0 2 1 0 2 2 2 0 2 1 2 0 0 1 0 0 0 1 0 2 1 0 1 0
 1 0 2 1 2 1 0 1]


In [11]:
#one hot encoding of labels
encoded_train_labels = utils.to_categorical(class_train_labels)
encoded_test_labels = utils.to_categorical(class_test_labels)

In [12]:
encoded_train_labels[0]

array([0., 0., 1.], dtype=float32)

In [13]:
encoded_test_labels[0]

array([0., 1., 0.], dtype=float32)

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [14]:
model = models.Sequential()
model.add(layers.Dense(8, activation='relu', input_shape=(4,)))
model.add(layers.Dense(3, activation='softmax'))

### STEP 4 : Compilation Step 

In [15]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['acc'])
model.fit(train_data, encoded_train_labels, epochs=100, batch_size=2)

Train on 105 samples
Epoch 1/100
105/105 [==============================] - 2s 18ms/sample - loss: 2.4838 - acc: 0.6000
Epoch 2/100
105/105 [==============================] - 0s 2ms/sample - loss: 1.8768 - acc: 0.6000
Epoch 3/100
105/105 [==============================] - 0s 2ms/sample - loss: 1.3538 - acc: 0.6190
Epoch 4/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.9961 - acc: 0.6476TA: 0s - loss: 1.0104 - acc: 0.642
Epoch 5/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.8126 - acc: 0.6476
Epoch 6/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.7216 - acc: 0.6762
Epoch 7/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.6456 - acc: 0.7524
Epoch 8/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.5948 - acc: 0.7524
Epoch 9/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.5554 - acc: 0.7905
Epoch 10/100
105/105 [==============================] - 0s 2ms

Epoch 83/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1395 - acc: 0.9619
Epoch 84/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1400 - acc: 0.9619
Epoch 85/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1364 - acc: 0.9524
Epoch 86/100
105/105 [==============================] - 0s 1ms/sample - loss: 0.1356 - acc: 0.9524
Epoch 87/100
105/105 [==============================] - 0s 1ms/sample - loss: 0.1338 - acc: 0.9524
Epoch 88/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1302 - acc: 0.9619
Epoch 89/100
105/105 [==============================] - 0s 1ms/sample - loss: 0.1283 - acc: 0.9619
Epoch 90/100
105/105 [==============================] - 0s 1ms/sample - loss: 0.1247 - acc: 0.9524
Epoch 91/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1213 - acc: 0.9619
Epoch 92/100
105/105 [==============================] - 0s 2ms/sample - loss: 0.1219 - acc: 0.9524
Epoch 93/1

### STEP 5 : Evaluation 

In [16]:
loss, acc = model.evaluate(test_data, encoded_test_labels, verbose=2)
print(acc)

45/1 - 0s - loss: 0.1068 - acc: 0.9778
0.9777778


### STEP 6 : Prediction 

In [29]:
i=19
prediction = model.predict_classes(test_data[i].reshape(1,4))

In [30]:
#checking
if prediction == 0:
    print(f'Data = {test_data[i]} => Prediction = Setosa => Actual label = {test_labels[i]}')
elif prediction == 1:
    print(f'Data = {test_data[i]} => Prediction = Versicolor => Actual label = {test_labels[i]}')
else:
     print(f'Data = {test_data[i]} => Prediction = Virginica => Actual label = {test_labels[i]}')

Data = [6.8 3.  5.5 2.1] => Prediction = Virginica => Actual label = Virginica
